package Problem_1_50;

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem_12 {
    public static void main(String[] args) {
        long count = 12360;
        long triNum = 0;
        int devNum = 0;
        int countDevNum = 500;

        while(true){
            for (long xx = 1; xx <= count; xx++) {
                triNum += xx;
            }
            for (long xx = triNum; xx>0; xx--){
                if(triNum%xx==0){
                    devNum++;
                }
            }
            if (devNum>countDevNum){
                break;
            }
            count++;
            devNum=0;
            triNum=0;
        }
        System.out.println(triNum);
    }
}
